### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Unity assets

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#101]
**What type of file would you like magika to detect?**
Unity assets file (.assets)

**What software can create/open these files?**
[Unity Engine](https://unity.com/), [Asset Studio](https://github.com/Perfare/AssetStudio), [Asset Ripper](https://github.com/AssetRipper/AssetRipper).

**Where can these files be found?**
Any Unity game.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
