### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] RPG Maker XP data

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#102]
**What type of file would you like magika to detect?**
RPG Maker XP data file (.xpdata)

**What software can create/open these files?**
[RPG Maker XP](https://www.rpgmakerweb.com/products/rpg-maker-xp), [rxdataToJSON](https://github.com/GamingLiamStudios/rxdataToJSON), [RpgMakerXPReader](https://github.com/JordanErick/RpgMakerXPReader), [rxdata transform](https://github.com/InabaByakko/rxdata-transform), [PKMNEssentialsPlugin](https://github.com/griest024/PKMNEssentialsPlugin), [rxdata map to json](https://github.com/Voxelstice/rxdata-map-to-json)

**Where can these files be found?**
Any RPG Maker XP game. Use [RPGMakerDecrypter](https://github.com/uuksu/RPGMakerDecrypter) if a game is encrypted in a rgssad file.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
