### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] RPG Maker XP rgssad file

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#103]
**What type of file would you like magika to detect?**
RPG Maker XP RGSS encrypted archive (.rgssad)

**What software can create/open these files?**
[RPG Maker RPG Maker XP](https://www.rpgmakerweb.com/products/rpg-maker-xp), [RPG Maker Decrypter](https://github.com/uuksu/RPGMakerDecrypter), [RGSS Decryptor](https://github.com/usagirei/RGSS-Decryptor)

**Where can these files be found?**
Many RPG Maker RPG Maker XP games. Use RPG Maker RPG Maker XP to compress your own.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
