### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] RPG Maker VX rgss1a file

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#104]
**What type of file would you like magika to detect?**
RPG Maker VX RGSS encrypted archive (.rgss1a)

**What software can create/open these files?**
[RPG Maker RPG Maker VX](https://www.rpgmakerweb.com/products/rpg-maker-vx), [RPG Maker Decrypter](https://github.com/uuksu/RPGMakerDecrypter), [RGSS Decryptor](https://github.com/usagirei/RGSS-Decryptor).

**Where can these files be found?**
Many RPG Maker RPG Maker VX games. Use RPG Maker RPG Maker VX to compress your own.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
