### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Ren'Py Archive

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#105]
**What type of file would you like magika to detect?**
Ren'Py Archive (.rpa)

**What software can create/open these files?**
[Ren'Py](https://www.renpy.org/), [RpaReader](https://github.com/OatmealDome/OatmealDome.RpaReader), [rpaextract](https://github.com/Kaskadee/rpaextract), [RPA Explorer](https://github.com/UniverseDevel/RPA-Explorer), [rpatool](https://github.com/shizmob/rpatool), [Game Resources Viewer](https://dinaki.itch.io/game-resources-viewer), [RPA Extract](https://iwanplays.itch.io/rpaex)

**Where can these files be found?**
Many [Ren'Py games](https://games.renpy.org/). Archive your own Ren'Py projects when building in Ren'Py.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
