### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] TOML

### ISSUE THREAD

**Issue by dbohdan** [google/magika#106]
**What type of file would you like magika to detect?**
 - [TOML](http://toml.io/)

**What software can create/open these files?**
- Cargo
- Hugo
- Poetry 
- setuptools
- Other Python packaging tools

**Where can these files be found?**
- [This very repository](https://github.com/google/magika/blob/2dea3b5bfc27c48dcd595ae41df59e724d6e7224/python/pyproject.toml) :-)
- Python projects
- Julia and Rust projects

**If possible, please provide a specification for this file type.**
- https://toml.io/en/v1.0.0
 
**Additional context**
Some files are valid and identical TOML and INI.

**Comment by reyammer** [comment]
Yep, we do miss this one. Thanks for reporting, marked as "to import to our KB" and closing it for now (see #152 for context). Thanks!
