### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Valve Pak

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#108]
**What type of file would you like magika to detect?**
Valve Pak file (.vpk)

**What software can create/open these files?**
VPK.exe, found in some Source games.
[GCFScape](https://nemstools.github.io/pages/GCFScape-Download.html)

**Where can these files be found?**
Many Source Engine games.

**If possible, please provide a specification for this file type.**
https://developer.valvesoftware.com/wiki/VPK_(file_format)
 
**Additional context**
https://developer.valvesoftware.com/wiki/VPK

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
