### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Godot Package

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#111]
**What type of file would you like magika to detect?**
Godot Package (.pck)

**What software can create/open these files?**
[Godot](https://godotengine.org/),
https://github.com/search?q=godot+pck&type=repositories.

**Where can these files be found?**
Many Godot games.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
