### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Nintendo Binary Revolution RESource

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#112]
**What type of file would you like magika to detect?**
Nintendo Binary Revolution RESource (.brres)

**What software can create/open these files?**
[BrawlCrate](https://github.com/soopercool101/BrawlCrate)

**Where can these files be found?**
Dump the ISO of any of [these Wii games](https://wiki.vg-resource.com/BRRES#List_of_games_using_the_format)

**If possible, please provide a specification for this file type.**
https://wiki.tockdom.com/wiki/BRRES_(File_Format), https://horizon.miraheze.org/wiki/.brres
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
