### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Source Engine Valve Map Format

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#113]
**What type of file would you like magika to detect?**
Source Valve Map Format file (.vmf)

**What software can create/open these files?**
Valve Hammer Editor, included with any Valve published Source Engine game on Steam.
[Hammer++](https://ficool2.github.io/HammerPlusPlus-Website/index.html)
[Slammin' Source Map Tools](https://knockout.chat/thread/992/1)

**Where can these files be found?**
Use [bspsrc](https://github.com/ata4/bspsrc) to decompile the BSP files of any Source Engine game. Use [GCFScape](https://nemstools.github.io/pages/GCFScape-Download.html) to extract even more BSPs from "dir.vpk" files. Make your own with the above tools.

**If possible, please provide a specification for this file type.**
https://developer.valvesoftware.com/wiki/VMF_(Valve_Map_Format)
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
