### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Blender file

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#114]
**What type of file would you like magika to detect?**
Blender save file (.blend)

**What software can create/open these files?**
[Blender](https://www.blender.org/download/)

**Where can these files be found?**
https://blendermarket.com/categories/models, https://www.turbosquid.com/Search/3D-Models/marketplace/blend, https://sketchfab.com/store/3d-models/blend?ref=store-home

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
