### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] COLLADA

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#116]
**What type of file would you like magika to detect?**
COLLADA file (.dae)

**What software can create/open these files?**
Many 3D modeling softwares.

**Where can these files be found?**
[COLLADA.zip](https://github.com/google/magika/files/14336166/COLLADA.zip)

**If possible, please provide a specification for this file type.**
https://www.collada.org/2008/03/COLLADASchema
 
**Additional context**
The included files are from examples of complete COLLADA models, given in the COLLADA Schema.

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
