### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Unreal Engine Asset

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#117]
**What type of file would you like magika to detect?**
Unreal Engine Asset (.uasset)

**What software can create/open these files?**
[Unreal Engine](https://www.unrealengine.com/en-US)

**Where can these files be found?**
[Unreal Marketplace](https://www.unrealengine.com/marketplace/en-US/store)

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
