### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] FBX

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#118]
**What type of file would you like magika to detect?**
AutoCad FBX model (.fbx)

**What software can create/open these files?**
Many 3D modeling softwares.

**Where can these files be found?**
https://www.turbosquid.com/Search/3D-Models/marketplace/fbx, https://sketchfab.com/store/3d-models/fbx?ref=store-home

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
