### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] OBJ

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#119]
**What type of file would you like magika to detect?**
Wavefront OBJ (.obj)

**What software can create/open these files?**
Almost any 3D application including [Maya](https://www.autodesk.com/products/maya/overview?term=1-YEAR&tab=subscription), [3ds Max](https://www.autodesk.com/products/3ds-max/overview?term=1-YEAR&tab=subscription), [Cinema 4D](https://www.maxon.net/en/cinema-4d), [MODO](https://www.foundry.com/products/modo), [ZBrush](https://www.maxon.net/en/zbrush), and [Blender](https://www.blender.org/).

**Where can these files be found?**
https://www.turbosquid.com/Search/3D-Models/marketplace/obj, https://sketchfab.com/store/3d-models/obj?ref=store-home

**If possible, please provide a specification for this file type.**
https://www.loc.gov/preservation/digital/formats/fdd/fdd000507.shtml#specs
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
