### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] JPEG2000

### ISSUE THREAD

**Issue by seth-shaw-asu** [google/magika#120]
**What type of file would you like magika to detect?**

JPEG2000 (aka JP2 and JPF)

**What software can create/open these files?**
- See the [JPEG.org site's list](https://jpeg.org/jpeg2000/software.html).
- IrfanView with a [plugin](https://www.irfanview.com/plugins.htm).
- XnView MP with a plugin
- OS X Preview app

**Where can these files be found?**
Examples:
 - Most digital libraries
 - Internet Archive books, e.g. https://archive.org/download/2018Fundamentals.ofPython/2018_fundamentals.of-python_jp2.zip
 - https://github.com/openpreserve/jpylyzer-test-files

**If possible, please provide a specification for this file type.**

 - https://jpeg.org/jpeg2000/workplan.html
 
**Additional context**
Currently misidentifies as MP4:
```
(env) dev:~/test_magika$ magika /data/Pictures/MBL_Album_3_pg_19b_1894_ten_scientists_inc._Lillie_Crane.jpf --json
[
    {
        "path": "/data/Pictures/MBL_Album_3_pg_19b_1894_ten_scientists_inc._Lillie_Crane.jpf",
        "dl": {
            "ct_label": "mp4",
            "score": 0.9982088804244995,
            "group": "video",
            "mime_type": "video/mp4",
            "magic": "ISO Media",
            "description": "MP4 media file"
        },
        "output": {
            "ct_label": "mp4",
            "score": 0.9982088804244995,
            "group": "video",
            "mime_type": "video/mp4",
            "magic": "ISO Media",
            "description": "MP4 media file"
        }
    }
]
```
File command is correct:
```
(env) dev:~/test_magika$ file /data/Pictures/MBL_Album_3_pg_19b_1894_ten_scientists_inc._Lillie_Crane.jpf 
/data/Pictures/MBL_Album_3_pg_19b_1894_ten_scientists_inc._Lillie_Crane.jpf: JPEG 2000 Part 1 (JP2)
```

**Comment by reyammer** [comment]
Thanks for reporting! Marked to be imported to our KB and closing it for now (see #152 for context). Thanks!
