### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Sketchup

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#121]
**What type of file would you like magika to detect?**
Sketchup file (.skp)

**What software can create/open these files?**
[Sketchup](https://www.sketchup.com/)

**Where can these files be found?**
https://3dwarehouse.sketchup.com/, https://sketchfab.com/store/3d-models/skp?ref=store-home

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
