### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] DOOM WAD

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#122]
**What type of file would you like magika to detect?**
DOOM "Where's All the Data" file (.wad)

**What software can create/open these files?**
[Ultimate Doom Builder](https://github.com/UltimateDoomBuilder/UltimateDoomBuilder), [Doom Explorer](http://doomutils.ucoz.com/)

**Where can these files be found?**
[doomworld](https://www.doomworld.com/forum/4-wad-releases-development/),
[idgames](https://www.doomworld.com/idgames/),
[archive.org 2020-03-22 DOOM](https://archive.org/details/2020_03_22_DOOM),
[DOOM CDs](https://archive.org/details/doom-cds),
[doomwadstation](https://www.doomwadstation.net/),
[ZDOOM](https://forum.zdoom.org/viewforum.php?f=41&sid=fec6908d863f341cb68b70c197ef5b71),
[realm667](https://www.realm667.com/index.php/en/),
[Rabbit's All-comers Mapping Project 2021](https://ramp2021.teamouse.net/download.php),
[Rabbit's All-comers Mapping Project 2022](https://ramp2022.teamouse.net/download.php),
[Rabbit's All-comers Mapping Project 2023](https://ramp2023.teamouse.net/download.php),
[vargskelethor DOOM mapping contest](https://vargskelethor.me/winners/),
[vargskelethor DOOM mapping contest](https://vargskelethor.me/winners2/),
[itch.io](https://itch.io/c/3460386/doom-mods),
[doomshack](https://doomshack.org/),
[Area-X1](https://x1.rfc1337.net/),
[euroboros](https://euroboros.net/zandronum/wads.php),
[allfearthesentinel](https://allfearthesentinel.com/zandronum/wads.php),
[Austral Doom Realms](https://audrealms.com/zandronum/wads.php),
[moddb/doom](https://www.moddb.com/games/doom),
[moddb/doom II](https://www.moddb.com/games/doom-ii/),
[dogsoft](https://doom.dogsoft.net/upload.php),
[wadseeker](https://doomseeker.drdteam.org/wadseeker.php)

**If possible, please provide a specification for this file type.**

 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
