### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Nintendo Binary caFe RESource

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#123]
**What type of file would you like magika to detect?**
Nintendo Binary caFe RESource (.bfres)

**What software can create/open these files?**
Anything in my [bfres collection](https://github.com/stars/MichaelHinrichs/lists/bfres), especially [Switch Toolbox](https://github.com/KillzXGaming/Switch-Toolbox).
[Wexos's Toolbox](https://wiki.tockdom.com/wiki/Wexos%27s_Toolbox)

**Where can these files be found?**
Dump the ISO of many Wii U or Switch games.

**If possible, please provide a specification for this file type.**
https://mk8.tockdom.com/wiki/BFRES_(File_Format), https://wiki.vg-resource.com/BFRES, https://wiki.oatmealdome.me/BFRES_(File_Format)
 
**Additional context**
Wii U and Switch BFRES files are a little different. Maybe add a separate detection for each.

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
