### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Nintendo Binary MoDeL files

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#125]
**What type of file would you like magika to detect?**
Nintendo Binary MoDeL (.bmd, .bdl)

**What software can create/open these files?**
[WindEditor](https://github.com/LordNed/WindEditor), [JStudio](https://github.com/LordNed/JStudio), [SuperBMD](https://github.com/Sage-of-Mirrors/SuperBMD), [WindViewer](https://github.com/pho/WindViewer), [j3dview](https://github.com/blank63/j3dview), [Takochu](https://github.com/shibbo/Takochu), [WiiExplorer](https://github.com/SuperHackio/WiiExplorer), [J3DUltra](https://github.com/Sage-of-Mirrors/J3DUltra), [JuniorsToolbox](https://github.com/JoshuaMKW/JuniorsToolbox), [Hack.io](https://github.com/SuperHackio/Hack.io)

**Where can these files be found?**
Dump the ISO of any of the following Gamecube or Wii games. They will be packed inside RARC files, and some RARC files will be compressed.
 - Luigi's Mansion
 - Super Mario Sunshine
 - The Legend of Zelda: Wind Waker
 - Pikmin 2
 - Mario Kart Double Dash
 - The Legend of Zelda: Twilight Princess
 - Super Mario Galaxy
 - Super Mario Galaxy 2

**If possible, please provide a specification for this file type.**
https://wiki.tockdom.com/wiki/BMD_and_BDL_(File_Format), https://wiki.cloudmodding.com/tww/BMD_and_BDL, https://pikmintkb.com/wiki/BMD_file, https://lmhacking.shoutwiki.com/wiki/Luigi%27s_Mansion:Docs/Model_Formats/BMD_and_BDL_(File_Format)
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
