### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Nintendo RARC archive

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#126]
**What type of file would you like magika to detect?**
Nintendo RARC file (.rarc)

**What software can create/open these files?**
[Takochu](https://github.com/shibbo/Takochu), [WiiExplorer](https://github.com/SuperHackio/WiiExplorer), [JuniorsToolbox](https://github.com/JoshuaMKW/JuniorsToolbox), [Hack.io](https://github.com/SuperHackio/Hack.io)

**Where can these files be found?**
Dump the ISO of any of the following Gamecube or Wii games. Some RARC files will be compressed into ".arc" or ".lzo" files.
 - Luigi's Mansion
 - Super Mario Sunshine
 - The Legend of Zelda: Wind Waker
 - Pikmin 2
 - Mario Kart Double Dash
 - The Legend of Zelda: Twilight Princess
 - Super Mario Galaxy
 - Super Mario Galaxy 2

**If possible, please provide a specification for this file type.**
http://www.amnoid.de/gc/Rarc.txt, https://kuribo64.net/wiki/?page=RARC,
https://wiki.tockdom.com/wiki/RARC_(File_Format),
https://lmhacking.shoutwiki.com/wiki/Luigi%27s_Mansion:Docs/BTI_(File_Format) (Don't mind the URL. This is the RARC page. It's just misnamed, apparently.)
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
