### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Lua

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#127]
**What type of file would you like magika to detect?**
Lua files (.lua)

**What software can create/open these files?**
https://github.com/LewisJEllis/awesome-lua?tab=readme-ov-file#implementations-interpreters-and-bindings
https://github.com/LewisJEllis/awesome-lua?tab=readme-ov-file#ides-and-plugins

**Where can these files be found?**
https://github.com/search?q=language%3ALua&type=repositories
https://steamdb.info/tech/SDK/Lua/

**If possible, please provide a specification for this file type.**
 
**Additional context**
https://www.lua.org

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
