### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] .DS_Store

### ISSUE THREAD

**Issue by birchb1024** [google/magika#128]
**What type of file would you like magika to detect?**

 Apple Mac .DS_Store files

**What software can create/open these files?**

macOS (I have Sonoma) 

**Where can these files be found?**

On any Apple Macintosh running macOS

**If possible, please provide a specification for this file type.**

https://en.wikipedia.org/wiki/.DS_Store
 
**Additional context**

https://0day.work/parsing-the-ds_store-file-format/

https://github.com/gehaxelt/Python-dsstore

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
