### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] GoldSrc Valve Map Format File

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#130]
**What type of file would you like magika to detect?**
GoldSrc Valve Map Format file (.vmf)

**What software can create/open these files?**
Hammer version 3, in the Half-Life SDK, available on Steam under the "Tools" section.
[J.A.C.K.](https://jack.hlfx.ru/en/main.html)
[Sledge](https://logicandtrick.github.io/sledge/)
[QuArK](https://quark.sourceforge.io/)

**Where can these files be found?**
Use [bspsrc](https://github.com/ata4/bspsrc) to decompile the BSP files of any GoldSrc game. Use [GCFScape](https://nemstools.github.io/pages/GCFScape-Download.html) to extract even more BSPs from ".wad" files. Make your own with the above tools.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
