### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] GoldSrc BSP

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#131]
**What type of file would you like magika to detect?**
GoldSrc Binary Space Partition version 30 (.bsp)

**What software can create/open these files?**
QBSP2

**Where can these files be found?**
Any GoldSrc game.
https://www.runthinkshootlive.com/
https://www.moddb.com/engines/goldsource/games
Make your own VMF files with Hammer version 3, in the Half-Life SDK, available on Steam under the "Tools" section, then compile them with QBSP2, also in the Half-Life SDK.

**If possible, please provide a specification for this file type.**
https://developer.valvesoftware.com/wiki/BSP_(GoldSrc)
https://hlbsp.sourceforge.net/index.php?content=bspdef
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
