### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Source BSP

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#132]
**What type of file would you like magika to detect?**
Source Engine Binary Space Partition (.bsp)

**What software can create/open these files?**
[VBSP](https://developer.valvesoftware.com/wiki/VBSP)

**Where can these files be found?**
Any Source Engine game. Use [GCFScape](https://nemstools.github.io/pages/GCFScape-Download.html) to extract even more BSPs from 'dir.vpk' files.
https://www.runthinkshootlive.com/
https://www.moddb.com/engines/source/games
Make your own Source VMF files, then compile them to BSP using [VBSP](https://developer.valvesoftware.com/wiki/VBSP), included with any Valve published Source Engine game on Steam.

**If possible, please provide a specification for this file type.**
https://developer.valvesoftware.com/wiki/BSP_(Source)
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
