### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Quake BSP

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#133]
**What type of file would you like magika to detect?**
Quake Binary Space Partition, version 29 (.bsp)

**What software can create/open these files?**
[QuakeED and Quake mapping tool](https://github.com/Jason2Brownlee/QuakeOfficialArchive)
[QuArK](https://quark.sourceforge.io/)
[trenchbroom](https://trenchbroom.github.io/)

**Where can these files be found?**
https://www.quakeworld.nu/forum/12/maps-textures
https://www.moddb.com/engines/quake-engine/games

**If possible, please provide a specification for this file type.**

 
**Additional context**
https://quakewiki.org/wiki/Quake_BSP_Format

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
