### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Quake 2 BSP

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#134]
**What type of file would you like magika to detect?**
Quake 2 Binary Space Partition, version 38 (.bsp)

**What software can create/open these files?**
[Quake 2 Tools](https://github.com/id-Software/Quake-2-Tools)
[QuArK](https://quark.sourceforge.io/)
[trenchbroom](https://trenchbroom.github.io/)

**Where can these files be found?**
https://www.quakeworld.nu/forum/12/maps-textures

**If possible, please provide a specification for this file type.**
https://www.flipcode.com/archives/Quake_2_BSP_File_Format.shtml
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
