### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Visual C project

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#136]
**What type of file would you like magika to detect?**
Visual C project (.vcxproj)

**What software can create/open these files?**
Visual Studio, CMake

**Where can these files be found?**
C++ app source code.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
