### ISSUE TITLE
Make magika available as a conda-forge package

### ISSUE THREAD

**Issue by prjemian** [google/magika#137]
With a python version on [PyPI](https://pypi.org/project/magika/), it would also be helpful to have a package on [conda-forge](https://conda-forge.org/docs/user/introduction/).  Is that planned?  ([There is not one at this time.](https://anaconda.org/search?q=magika))

**Comment by reyammer** [comment]
We don't have it but we'd love if someone would take this up! Edited the title of the issue and added proper labels.

**Comment by invernizzi** [comment]
There's a package now :)
Not sure how it got there (I guess it's automatically getting pulled from Pypi).

**Comment by prjemian** [comment]
This process is not automatic.  Apparently, it was accepted into conda-forge about two weeks ago.  To date, downloaded 33 times.

The [recipe](https://github.com/conda-forge/magika-feedstock/blob/main/recipe/meta.yaml) for the [conda-forge package](https://anaconda.org/conda-forge/magika#L52) lists @thewchan as the maintainer.  The recipe [pulls](https://github.com/conda-forge/magika-feedstock/blob/acb133a66b6c291f0678f4499d9b8b952e6ff3ab/recipe/meta.yaml#L9) the package from PyPI.

Thanks go to Matt!

**Comment by invernizzi** [comment]
Great! Thank you for the explanation. And thank you Matt!

**Comment by thewchan** [comment]
Hi all, I'm happy to add folks to the maintainer of the Conda Forge feedstock of Magika here: https://github.com/conda-forge/magika-feedstock/. Let me know if any of the developers here are interested, no pressure obviously. Thanks!
