### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Visual Studio Solution

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#138]
**What type of file would you like magika to detect?**
Visual Studio Solution (.sln)

**What software can create/open these files?**
Visual Studio

**Where can these files be found?**
Source code of any C++ or C# app, as long as the devs don't SUCK, and leave you to set one up yourself!

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
