### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] .pdb

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#139]
**What type of file would you like magika to detect?**
Program Debug Database (.pdb)

**What software can create/open these files?**
Visual Studio.

**Where can these files be found?**
Any Visual Studio project, after compiling.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
