### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Type Script

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#141]
**What type of file would you like magika to detect?**
Type Script code (.ts)

**What software can create/open these files?**
Many IDEs, any text editor.

**Where can these files be found?**
https://github.com/search?q=language%3ATypeScript&type=repositories

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
