### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Visual Studio C# Project

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#143]
**What type of file would you like magika to detect?**
Visual Studio C# Project (.csproj)

**What software can create/open these files?**
Visual Studio

**Where can these files be found?**
https://github.com/search?q=language%3AC%23+&type=repositories

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
