### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Rust

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#144]
**What type of file would you like magika to detect?**
Rust code (.rs)

**What software can create/open these files?**
Many IDEs, any text editor.

**Where can these files be found?**
https://github.com/search?q=language%3ARust+&type=repositories

**If possible, please provide a specification for this file type.**
 
**Additional context**
https://www.rust-lang.org/

**Comment by reyammer** [comment]
Magika already supports rust (https://github.com/google/magika/blob/main/docs/supported-content-types-list.md). Closing this for now, but if you created this issue because you run in a very high number of misdetections, please re-open and let's discuss. Thanks!
