### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] CMake

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#146]
**What type of file would you like magika to detect?**
CMake Source File (.cmake)

**What software can create/open these files?**
Examples:
[CMake](https://cmake.org/)

**Where can these files be found?**
https://github.com/search?q=language%3Acmake&type=code

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
