### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] gitignore

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#149]
**What type of file would you like magika to detect?**
gitignore file (.gitignore)

**What software can create/open these files?**
[git cli](https://git-scm.com/downloads)
[GitHub cli](https://cli.github.com/)
https://git-scm.com/downloads/guis

**Where can these files be found?**
https://github.com/github/gitignore
https://github.com/toptal/gitignore

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see #152 for context. Thanks!
