### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Visual Studio Solution User Options

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#150]
**What type of file would you like magika to detect?**
Visual Studio Solution User Options (.suo)

**What software can create/open these files?**
Visual Studio

**Where can these files be found?**
Some Visual Studio projects.

**If possible, please provide a specification for this file type.**

**Additional context**

**Comment by reyammer** [comment]
As discussed in #152, labeled with "content type to import in KB" and closing it for now. Thanks for reporting!
