### ISSUE TITLE
Consider removing MIME type column from the supported content type list

### ISSUE THREAD

**Issue by reyammer** [google/magika#154]
As discussed [here](https://github.com/google/magika/blob/main/docs/faq.md#q-what-is-the-problem-with-relying-on-mime-types-for-automated-workflows), MIME types are not a good fit for automated workflows. We may want to remove the MIME type column in the [supported content types list](https://github.com/google/magika/blob/main/docs/supported-content-types-list.md) to discourage additional usage.

**Comment by devilkadabra69** [comment]
well i have removed the whole column -> "MIME Type" and now the new table contains the column ->Index Content Type Label and Description

**Comment by reyammer** [comment]
Closed by #157.
