### ISSUE TITLE
Setup a github action (or similar) to apply the "needs triage" label to every new external github issue

### ISSUE THREAD

**Issue by reyammer** [google/magika#155]
This helps us tracking which issue still needs the first pass.

Checking online it seems there is no way to apply a label by default to every template, and it seems the way to go is to add a github action?

Ideally, the label would not be applied if one of the current maintainers is opening it. But that's not so important...

**Comment by Mohit-Gaur** [comment]
@reyammer I'd be interested in picking up this issue if you're accepting contributions

**Comment by reyammer** [comment]
Assigned to you, thanks!

**Comment by Mohit-Gaur** [comment]
There are two ways to determine if an issue creator is a maintainer:

1. Use the GitHub API to check if the user is a collaborator on the repo.
2. Use a CODEOWNERS file to maintain a list of project maintainers. More info [here](https://github.blog/2017-07-06-introducing-code-owners/).

Of course, we would be using GitHub actions in both cases.
