### ISSUE TITLE
Support for SRT file detection

### ISSUE THREAD

**Issue by doggy8088** [google/magika#176]
**What type of file would you like magika to detect?**

SubRip Subtitle file (.srt)

> An SRT file, or SubRip Subtitle file, is one of the most popular subtitle file formats for video content. These plain text files include the text of the subtitles in sequence, along with the start and end timecodes. However, an SRT file does not contain any video or audio content. That's why the file sizes are so small.
>
> -- from [What Is an SRT File?](https://mailchimp.com/resources/what-is-an-srt-file/)

**What software can create/open these files?**
Most of the video player could open video comes with a `.srt` file. Such as [PotPlayer](https://potplayer.daum.net/). Also, [YouTube Studio](https://studio.youtube.com/) is able to upload a video with a SRT file (.srt) for subtitles.

The .srt is simply a text file, so any text editor can open it.

**Where can these files be found?**
I have a sample SRT file here: https://gist.github.com/doggy8088/74539b8454c35b641b8875375eb82d36

You can download almost any SRT file of a video from YouTube. Use this tool: <https://views4you.com/tools/youtube-subtitles-downloader/>

**If possible, please provide a specification for this file type.**
 - <https://en.wikipedia.org/wiki/SubRip>
 - <https://www.loc.gov/preservation/digital/formats/fdd/fdd000569.shtml>
 - <https://docs.lokalise.com/en/articles/5365539-subrip-srt>
 
**Additional context**

![image](https://github.com/google/magika/assets/88981/1f572648-2052-46ad-89bf-8bddf7240d61)

**Comment by reyammer** [comment]
Super helpful. Tagging and closing (see #152 for context). Thank you!
