### ISSUE TITLE
[Misdetection] AppleScript file misdetected as MS Visual Basic source (VBA)

### ISSUE THREAD

**Issue by andrewcrook** [google/magika#181]
**What should the file have been detected as? What has the file been misdetected as?**
Ex. "HTML pages are being mistaken for generic XML files.", "C# code misdetected as Java.", or "Can't tell the difference between exe and dll files."

**Please link or attach the misdetected file below** (Do NOT upload PII!)
Placeholder.zip

**Additional context**

**Comment by reyammer** [comment]
Thanks for reporting! we don't have applescript, tagging & closing this issue as a reminder to consider it for next version (see #152 for context). Thanks!
