### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] coff object file

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#183]
**What type of file would you like magika to detect?**
coff object file (.obj)

**What software can create/open these files?**
Visual Studio

**Where can these files be found?**
The build folders of C++ projects. Here are the ones I found obj files in on my pc.
 - [Torque3D](https://github.com/GarageGames/Torque3D)
 - [urho3d](https://github.com/urho3d/urho3d)
 - [liblcf](https://github.com/EasyRPG/liblcf)
 - [gameplay](https://github.com/gameplay3d/gameplay)
 - [GDevelop](https://github.com/4ian/GDevelop)
 - [assimp](https://github.com/assimp/assimp)
 - [OpenToshi](https://github.com/AdventureT/OpenToshi)
 - [meshlab](https://github.com/cnr-isti-vclab/meshlab)
 - [Enemy Territory: Quake Wars 1.5 SDK](https://archive.org/details/enemy-territory-quake-wars-1.5-sdk)
 - [FBX SDK](https://aps.autodesk.com/developer/overview/fbx-sdk)

**If possible, please provide a specification for this file type.**
 https://wiki.osdev.org/COFF

**Additional context**

**Comment by reyammer** [comment]
we already do have coff...?

**Comment by MichaelHinrichs** [comment]
Dang it. I forgot to check.
