### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Outlook MSG file format

### ISSUE THREAD

**Issue by Maijin** [google/magika#218]
**What type of file would you like magika to detect?**
Examples:
 - Outlook MSG file format (.msg)

**What software can create/open these files?**
Examples:
 - Email readers

**Where can these files be found?**
Examples:
 - Email forward
 - PSTs

**If possible, please provide a specification for this file type.**
Examples:
 - https://www.loc.gov/preservation/digital/formats/fdd/fdd000379.shtml
 
**Additional context**

**Comment by reyammer** [comment]
Is this something different than "outlook", which we should already support? https://github.com/google/magika/blob/main/docs/supported_content_types_list.md

**Comment by Maijin** [comment]
Ah yes - may be worth adding msg in the table, I'll open a PR
