### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] jsonl format

### ISSUE THREAD

**Issue by Maijin** [google/magika#219]
**What type of file would you like magika to detect?**
Examples:
 - JSON Lines (.jsonl)

**What software can create/open these files?**
Examples:
 - BigQuery

**Where can these files be found?**
Examples:
 - Database dump
 - API

**If possible, please provide a specification for this file type.**
Examples:
 - https://jsonlines.org/examples/

**Comment by reyammer** [comment]
See also #57 

Added to the list to be considered. Tagged and closing (see #152 for context). Thanks!
