### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Audacity Project

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#225]
**What type of file would you like magika to detect?**
Audacity Project (.aup)

**What software can create/open these files?**
[Audacity](https://www.audacityteam.org/)

**Where can these files be found?**
Make your own.

**If possible, please provide a specification for this file type.**
All I could find is that "Audacity 3.x project files are based on an [SQLite](http://justsolve.archiveteam.org/wiki/SQLite) database. The application ID stored in the database header at offset 68 is AUDY string or 41554459 hexadecimal." like that explains everything. IDK, maybe it does, but not to me, because I don't understand it.
 
**Additional context**
http://justsolve.archiveteam.org/wiki/Audacity_Project_Format

**Comment by corkamig** [comment]
Thanks, we'll consider it!

The v3 format's extension is actually `aup3`: `.aup` is used until V2, which is using XML.
The `AUDY` string at offset 68 is not present in typical `.sqlite` files.
