### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] LMMS Project

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#226]
**What type of file would you like magika to detect?**
LMMS Project (.mmpz)

**What software can create/open these files?**
[LMMS](https://lmms.io/)

**Where can these files be found?**
https://lmms.io/lsp/?action=browse&category=Projects

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by corkamig** [comment]
Thanks! We'll consider it!
