### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] ICS file

### ISSUE THREAD

**Issue by gelim** [google/magika#227]
**What type of file would you like magika to detect?**
Examples:
 - " vCalendar calendar file"
 

**What software can create/open these files?**:
 - Calendar applications
 
**Where can these files be found?**
- [random internet example
](https://www.igloolabserver.com/ics/invite.ics)

**If possible, please provide a specification for this file type.**
- [wikipedia
](https://en.wikipedia.org/wiki/ICalendar)

**Comment by corkamig** [comment]
Thanks! We'll definitely consider it for next versions.
