### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] ICNS Mac OS X icon

### ISSUE THREAD

**Issue by gelim** [google/magika#228]
**What type of file would you like magika to detect?**
 - "Mac OS X icon"

**What software can create/open these files?**
  - "Any image viewer/editor"

**Where can these files be found?**
- In a Mac OS X based system
- [random internet example](https://github.com/stinoga/app.icns/tree/master/icns)

**If possible, please provide a specification for this file type.**
- [Wikipedia](https://en.wikipedia.org/wiki/Apple_Icon_Image_format#:~:text=The%20Apple%20Icon%20Image%20format,%3A%20open%20and%20closed%20folders)

**Comment by corkamig** [comment]
Thanks! We'll consider it for next versions!
