### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] .REG Windows Registry

### ISSUE THREAD

**Issue by gelim** [google/magika#229]
**What type of file would you like magika to detect?**
- REG Windows Registry 

**What software can create/open these files?**:
 - Windows Registry compatible viewer/editor

**Where can these files be found?**
- on a Windows host
- [random GH reg file](https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/Win7Samples/security/credentialproviders/sampleallcontrolscredentialprovider/Register.reg)

**If possible, please provide a specification for this file type.**
- [fileformat.com](https://docs.fileformat.com/system/reg/)

**Comment by corkamig** [comment]
Thanks! We'll consider them (various regedit versions).
