### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Apache Parquet file

### ISSUE THREAD

**Issue by gelim** [google/magika#230]
**What type of file would you like magika to detect?**
 - "Apache Parquet file"
 
**What software can create/open these files?**
- [apache parquet](https://parquet.apache.org/)

**Where can these files be found?**
- [huggingface](https://huggingface.co/datasets/huggingface/map-test/blob/732415a69f3fbe1a567b5d44c4eca8fb96956852/huggingface--map-test/csv-train.parquet)

**If possible, please provide a specification for this file type.**
-  [spec from github](https://github.com/apache/parquet-format)

**Comment by corkamig** [comment]
Thanks! We'll consider adding it in next versions.
