### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] ABAP

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#231]
**What type of file would you like magika to detect?**
ABAP

**What software can create/open these files?**
Many IDEs.

**Where can these files be found?**
https://github.com/search?q=language%3AABAP&type=repositories

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by corkamig** [comment]
Thanks! We'll consider it.

FTR: `Advanced Business Application Programming` by SAP (1983) -  https://en.wikipedia.org/wiki/ABAP
