### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] ABNF

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#233]
**What type of file would you like magika to detect?**
ABNF

**What software can create/open these files?**
Many IDEs.

**Where can these files be found?**
https://github.com/search?q=language%3AABNF&type=code

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by corkamig** [comment]
Thanks! Definitely to be considered for next versions!
