### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] AGS Script

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#234]
**What type of file would you like magika to detect?**
AGS Script (.ash .asc) 

**What software can create/open these files?**
Many IDEs.

**Where can these files be found?**
https://github.com/search?q=language%3AAGS+Script&type=repositories

**If possible, please provide a specification for this file type.**
 
**Additional context**
Adventure Game Studio: https://adventuregamestudio.github.io/ags-manual/index.html

**Comment by corkamig** [comment]
Thanks! We'll consider it.
