### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] AIDL

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#235]
**What type of file would you like magika to detect?**
AIDL

**What software can create/open these files?**
Many IDEs.

**Where can these files be found?**
https://github.com/search?q=language%3AAIDL&type=code

**If possible, please provide a specification for this file type.**
 [Android Interface Definition Language](https://developer.android.com/develop/background-work/services/aidl)

**Additional context**
```
// IRemoteService.aidl
package com.example.android;

// Declare any non-default types here with import statements.

/** Example service interface */
interface IRemoteService {
    /** Request the process ID of this service. */
    int getPid();

    /** Demonstrates some basic types that you can use as parameters
     * and return values in AIDL.
     */
    void basicTypes(int anInt, long aLong, boolean aBoolean, float aFloat,
            double aDouble, String aString);
}
```

**Comment by corkamig** [comment]
Thanks! We'll consider it!
