### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Dicom

### ISSUE THREAD

**Issue by ti3x** [google/magika#237]
**What type of file would you like magika to detect?**
DICOM (.dcm)

**What software can create/open these files?**

Libs: 
- PyDicom (Python)
- DCMTK (C++)

Viewers:
- Horos
- Osirix

**Where can these files be found?**

- https://www.kaggle.com/code/micheldc55/how-to-read-dcm-dicom-data#
- https://www.kaggle.com/code/srikanthpotukuchi/understanding-dcm-files-using-pydicom
- https://www.kaggle.com/code/rude009/working-with-dicom-data

**Here are some key resources for the DICOM file specification**

- Official DICOM Standard Website: https://www.dicomstandard.org/current
- PyDicom Documentation: https://pydicom.github.io/pydicom/dev/reference/generated/pydicom.dataelem.DataElement.html (Provides detailed information about specific DICOM data elements and their usage)
- DCMTK Documentation: https://dicom.offis.de/dcmtk.php.en (Offers extensive documentation for the DCMTK library, which can be used to work with DICOM files)

 
**Additional notes:**

- DICOM files can be large and complex, and specialized software is often required to open and view them properly.
- Due to the sensitive nature of medical information, DICOM files may have access restrictions and should only be shared with authorized personnel.

**Comment by corkamig** [comment]
Thanks! We'll do our best!
