### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Tcl source code

### ISSUE THREAD

**Issue by dbohdan** [google/magika#240]
**What type of file would you like magika to detect?**
- [Tcl](https://en.wikipedia.org/wiki/Tcl) source code (`.tcl`, `.test`)

**What software can create/open these files?**
- Various implementations of the Tcl programming language, like Tcl 8.6, Jim Tcl, JTcl, etc.

**Where can these files be found?**
- [Tcllib](https://core.tcl-lang.org/tcllib/), the Tcl standard library
- The [SQLite test harness](https://sqlite.org/src/dir?ci=trunk&name=test) ([information](https://www.sqlite.org/testing.html))
- [MacPorts](https://core.tcl-lang.org/tcllib/ticket)
- [GitHub projects](https://github.com/search?q=language%3Atcl&type=repositories&s=stars&o=desc)

**If possible, please provide a specification for this file type.**
The ["Dodekalogue"](https://www.tcl-lang.org/man/tcl/TclCmd/Tcl.htm) is an informal specification of modern Tcl syntax.

**Comment by corkamig** [comment]
Thanks for all the info!

**Comment by qwertychouskie** [comment]
Was this meant to be closed?  As far as I can tell, Tcl is still not supported.

**Comment by reyammer** [comment]
@qwertychouskie, for context: we are tracking missing content types with a tag, and then we import it in our knowledge base. And then we close the issue to clean things up. TCL is indeed not supported in v1, but it looks like we'll be able to add it for v2 of the model.
