### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Drawing Exchange Format

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#245]
**What type of file would you like magika to detect?**
Drawing Exchange Format (.dxf)

**What software can create/open these files?**
[Adobe Illustrator](https://www.adobe.com/products/illustrator.html), [CorelDRAW](https://www.coreldraw.com/), [Autodesk viewer](https://viewer.autodesk.com/), [eDrawings app](https://apps.apple.com/tr/app/edrawings/id1209754386?mt=12), [TurboCAD](https://www.turbocad.com/), [Onshape](https://www.onshape.com).

**Where can these files be found?**
https://www.turbosquid.com/Search/3D-Models/dxf
https://free3d.com/premium-3d-models/dxf
https://www.cgtrader.com/3d-models?file_types[]=7
https://3axis.co/dxf-files
https://www.dxfforcnc.com
https://open3dmodel.com/3d-models/dxf

**If possible, please provide a specification for this file type.**
http://images.autodesk.com/adsk/files/autocad_2012_pdf_dxf-reference_enu.pdf
 
**Additional context**
[Learn About DXF Files | Adobe](https://www.adobe.com/creativecloud/file-types/image/vector/dxf-file.html#:~:text=DXF%20is%20short%20for%20Drawing,3D%20drawings%20during%20product%20design.)

**Comment by corkamig** [comment]
Thanks!
