### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Corel DRaw vectors

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#246]
**What type of file would you like magika to detect?**
Corel DRaw vectors (.cdr)

**What software can create/open these files?**
[CorelDRAW](https://www.coreldraw.com/en/)

**Where can these files be found?**
https://3axis.co/free-cdr-files/

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by corkamig** [comment]
Thanks!

Note to self: either ZIP-based or Riff-based - http://fileformats.archiveteam.org/wiki/CorelDRAW
