### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] MPEG-4 Audio

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#263]
**What type of file would you like magika to detect?**
MPEG-4 Audio (.m4a)

**What software can create/open these files?**
iTunes, Windows Media Player, [VLC media player](https://www.videolan.org/vlc/), [foobar](https://www.foobar2000.org/).

**Where can these files be found?**
Music albums bought on iTunes.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by corkamig** [comment]
Thanks!
