### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] mtl

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#266]
**What type of file would you like magika to detect?**
Wavefront material (.mtl)

**What software can create/open these files?**
Almost any 3D application including [Maya](https://www.autodesk.com/products/maya/overview?term=1-YEAR&tab=subscription), [3ds Max](https://www.autodesk.com/products/3ds-max/overview?term=1-YEAR&tab=subscription), [Cinema 4D](https://www.maxon.net/en/cinema-4d), [MODO](https://www.foundry.com/products/modo), [ZBrush](https://www.maxon.net/en/zbrush), and [Blender](https://www.blender.org/).

**Where can these files be found?**
They come with OBJ files.
https://www.turbosquid.com/Search/3D-Models/marketplace/obj,
https://sketchfab.com/store/3d-models/obj?ref=store-home,
[https://www.cgtrader.com/search?file_types[]=12](https://www.cgtrader.com/search?file_types%5B%5D=12),
https://free3d.com/3d-models/obj,
https://www.freepik.com/3d-models,
https://open3dmodel.com/3d-models/obj.

**If possible, please provide a specification for this file type.**
https://paulbourke.net/dataformats/mtl/
 
**Additional context**
https://people.computing.clemson.edu/~dhouse/courses/405/docs/brief-mtl-file-format.html#:~:text=Material%20Library%20File%20(.mtl),surfaces%20and%20vertices%20of%20objects.

**Comment by corkamig** [comment]
Thank you!
