### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Sound Font 2

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#277]
**What type of file would you like magika to detect?**
Sound Font 2 (.sf2)

**What software can create/open these files?**
[lmms](https://lmms.io/), [polyphone](https://www.polyphone-soundfonts.com/).

**Where can these files be found?**
https://www.williamkage.com/snes_soundfonts/, https://musical-artifacts.com/artifacts?formats=sf2, https://www.polyphone-soundfonts.com/download-soundfonts.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by corkamig** [comment]
Note to self: Riff-based!
