### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Virtual Studio Technology (VST -> PE/MachO)

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#278]
**What type of file would you like magika to detect?**
Virtual Studio Technology (.vst)

**What software can create/open these files?**
[LMMS](https://lmms.io/), [FL Studio](https://www.image-line.com/)

**Where can these files be found?**
https://itch.io/c/3315729/virtual-studio-technology, https://www.producersphere.com/category/plugins/, https://midination.com/category/vst/, https://integraudio.com/category/plugins/, https://musicproductionnerds.com/best-professional-vst-plugins-for-music-production, https://thehomerecordings.com/category/free-vst-plugins/, https://thehomerecordings.com/category/vst-instrument/, https://thehomerecordings.com/category/vst-effects/, https://keyboardkraze.com/category/virtual-instruments/, https://keyboardkraze.com/best-free-piano-vsts/, https://keyboardkraze.com/best-piano-vst-plugins/, https://keyboardkraze.com/best-fl-studio-vst-plugins/, https://keyboardkraze.com/best-electric-guitar-vsts/, https://www.edmprod.com/free-vst-plugins/, https://get.output.com/vst_plugin, https://producerhive.com/category/buyer-guides/vst/, https://splice.com/plugins/, https://plugins4free.com/, https://www.pluginboutique.com/, https://www.steinberg.net/vst-instruments/, https://bedroomproducersblog.com/free-vst-plugins/, https://www.native-instruments.com/en/catalog/software/, https://www.native-instruments.com/en/specials/komplete/best-vst-plugins/, https://www.native-instruments.com/en/specials/free-vst-plugins/, https://pulse.audio/product-category/format/plugin/, https://musicsoftwaredeals.com/, https://www.soundtoys.com/product/, https://www.fabfilter.com/products, https://www.plugin-alliance.com/, https://www.image-line.com/fl-studio/plugins/, https://99sounds.org/vst-plugins/, https://soniccharge.com/products, https://github.com/robbert-vdh/nih-plug.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by corkamig** [comment]
They're actually standard executables: dll or mach-o
