### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Minecraft Named Binary Tag

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#279]
**What type of file would you like magika to detect?**
Named Binary Tag (.nbt)

**What software can create/open these files?**
[nbt-studio](https://github.com/tryashtar/nbt-studio), [Online NBT editor](https://gamertools.net/tools/13), [NBT Editor](https://nbt.mcph.to/), [webNBT](https://irath96.github.io/webNBT/), [NBTExplorer](https://github.com/jaquadro/NBTExplorer), [NBTEdit](https://github.com/Jay113355/NBTEdit).

**Where can these files be found?**
Minecraft.
To do: Write a better answer in the morning.

**If possible, please provide a specification for this file type.**
https://web.archive.org/web/20110723210920/http://www.minecraft.net/docs/NBT.txt (outdated)
 
**Additional context**
https://minecraft.fandom.com/wiki/NBT_format

**Comment by corkamig** [comment]
Thanks! With many inconsistencies across versions!
