### ISSUE TITLE
python: make sure tests fail when the test cases include file types magika doesn't support

### ISSUE THREAD

**Issue by reyammer** [google/magika#284]

**Comment by gaby** [comment]
@reyammer The python package needs a new release, the one on Pypi doesn't work with py3.12 and doesn't have the typing fixes for 3.8/3.9

**Comment by reyammer** [comment]
@gaby yep, working on it right now.

And closing this, fixed in https://github.com/google/magika/commit/91cfb0aa83abd5ae260308a27b7e844ca95eee12
