### ISSUE TITLE
Add "is_text" to magika's output

### ISSUE THREAD

**Issue by reyammer** [google/magika#294]
There are clients that use magika to determine whether a file is text vs. binary. See #217.

We'll support this use case by adding is_text to the magika's output so that clients don't need to add additional logic just for this. We already have this info and it's easy to expose.

**Comment by nhonx** [comment]
https://github.com/google/magika/pull/298
Is this what we want?

**Comment by reyammer** [comment]
mmm, not really (but thanks for the PR!). The problem with that approach is that we would need to add (and support) a new CLI. My idea was instead to add a new field to the output json (the one you see with `--jsonl` or `--json`); the idea is to have a `is_text` field. Makes sense?

**Comment by nhonx** [comment]
> mmm, not really (but thanks for the PR!). The problem with that approach is that we would need to add (and support) a new CLI. My idea was instead to add a new field to the output json (the one you see with `--jsonl` or `--json`); the idea is to have a `is_text` field. Makes sense?

It makes sense, but I think sometimes users want to output it to CLI for pipe it with `awk` or something. If so, only adding new field to json will not help so much, correct?
If you want, I will add to the PR with the new field to JSON output. Is that ok?

**Comment by reyammer** [comment]
I have a PR ready for adding is_text to json, so don't worry. But I'd like to understand a bit more what would be the use case and the expected usage. Can you provide a concrete example on how you chain magika with awk? The other thought: if it's supposed to be used in an automated way, then the output should likely be something easily parsable (like json, e.g., with `jq`), and not a modification of the human description (as in your PR)?

**Comment by reyammer** [comment]
Implemented this in https://github.com/google/magika/commit/618581afd85842e5d844e0e22225c10a08d74d30.

Closing this issue, opening another issue to discuss your use case.
