### ISSUE TITLE
Discuss adding `--check-text` CLI option

### ISSUE THREAD

**Issue by reyammer** [google/magika#303]
References: #298, #294.

nhonx: "It makes sense, but I think sometimes users want to output it to CLI for pipe it with awk or something. If so, only adding new field to json will not help so much, correct?"

My question: But I'd like to understand a bit more what would be the use case and the expected usage. Can you provide a concrete example on how you chain magika with awk? The other thought: if it's supposed to be used in an automated way, then the output should likely be something easily parsable (like json, e.g., with jq), and not a modification of the human description (as in your PR)?

/cc @nhonx

**Comment by reyammer** [comment]
Still can't of any use case / or any way in which having "is text" as human output is better than json output. Since there is no new input, closing for now. @nhonx feel free to reopen if you have more ideas, thanks!

**Comment by nhonx** [comment]
Hi @reyammer , sorry for late response.
Of course, I agree that json output could be solution for almost all cases. However, when working with CLI, many people will be familiar with pipe and awk and feel more convenient with them.
Let check this case: I want to count how many Binary and Text file in a folder
`magika -r ../tests_data/ --check-text | awk '{print $NF}' | sort | uniq -c`
Output:
```
  41 (binary)
  21 (text)
```
I think it will faster than we return JSON and process the JSON with jq or sth.
