### ISSUE TITLE
BUG: Possible typo

### ISSUE THREAD

**Issue by grant-d** [google/magika#306]
I was looking for the value of a `const` and noticed this possible bug. Second `if` is a duplicate of the first.
https://github.com/google/magika/blob/36a867104d121cd058827e3762288d4f87461a36/js/src/config.ts#L48-L51

**Comment by reyammer** [comment]
it indeed seems a typo. Thanks for reporting! Assigning to @invernizzi

**Comment by invernizzi** [comment]
Thank you! Thankfully, it's dead code (no effect on outputs)
