### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Rust source code (.rs)

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#384]
**What type of file would you like magika to detect?**
Rust source code (.rs)

**What software can create/open these files?**
https://www.rust-lang.org/tools

**Where can these files be found?**
https://github.com/search?q=language%3ARust&type=repositories

**If possible, please provide a specification for this file type.**
https://doc.rust-lang.org/std/index.html
 
**Additional context**

**Comment by reyammer** [comment]
Hello @MichaelHinrichs! Thanks for all opening all issues, I appreciate your help. But I'm falling behind properly triaging them, we are already considering many of these for v2 (and some are already present even for v1), and we are currently busy training a new model. I think we have enough content type ideas for many versions ahead, no need to open issues any more, our queue is full :-) I'll try to find the time to triage them soon, but for the moment we can suspend collecting new ideas, thank you!
