### ISSUE TITLE
[Feature Request] COBOL File Support

### ISSUE THREAD

**Issue by razfriman** [google/magika#39]
Per the project README, I'd like to open a feature request to support an expanded set of file types. Specifically I would be interested to support the **COBOL** language.

I see per the support content types list it is not currently supported:

https://github.com/google/magika/blob/120205323e260dad4e58778093fb220aa1991c2b/docs/supported-content-types-list.md?plain=1#L17

Would it be possible to support this language?

Thanks!

**Comment by reyammer** [comment]
Thanks for the feedback! Noting it down to try to include it for v2.
