### ISSUE TITLE
sqlite3 files aren't detected correctly

### ISSUE THREAD

**Issue by ujaehrig** [google/magika#40]
Hi. Interesting project! 

When I run it against one of my directories, I found it has some problems with sqlite3 files. 

Simple example: 
```
sqlite3 y.db 'create table y ( int id )' ; magika y.db ; file y.db

y.db: ISO 9660 CD-ROM filesystem data (archive)
y.db: SQLite 3.x database, last written using SQLite version 3037002, file counter 1, database pages 2, cookie 0x1, schema 4, UTF-8, version-valid-for 1
```

In most cases, a sqlite3 file is detected as ISO 9660, but I also had one case of `RedHat Package Manager archive`

**Comment by diimdeep** [comment]
looks pretty much broken

```
cd ~/Library/Application\ Support/CallHistoryDB/
magika -s CallHistory.storedata 
CallHistory.storedata: ISO 9660 CD-ROM filesystem data (archive) 99%

file CallHistory.storedata                                               
CallHistory.storedata: SQLite 3.x database, last written using SQLite version 3032003

binwalk CallHistory.storedata                                             
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             SQLite 3.x database,
```

**Comment by reyammer** [comment]
Thanks @ujaehrig. sqlite is not in the currently supported content types, but noting this down for v2. Thanks!

**Comment by ujaehrig** [comment]
Hi @reyammer, thank you. I had seen the document of the supported filetypes too late (maybe should be show more prominent on the page ;-) , but was surprised it's not supported yet. But thank you for the heads-up! 

I'm closing the ticket for the moment.

**Comment by reyammer** [comment]
no worries. tagged as "to import to our KB" so that we keep this into account (see #152 for context). sqlite is indeed very relevant and should be supported. thanks for reporting!
