### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Gleam

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#401]
**What type of file would you like magika to detect?**
Gleam code (.gleam)

**What software can create/open these files?**
https://gleam.run/getting-started/installing/#editor-plugins

**Where can these files be found?**
https://github.com/search?q=language%3AGleam&type=repositories

**If possible, please provide a specification for this file type.**
https://gleam.run/documentation/
 
**Additional context**
https://gleam.run/community/

**Comment by corkamig** [comment]
Thanks - noted!
