### ISSUE TITLE
Consider yanking the 0.1.0 release

### ISSUE THREAD

**Issue by ismail** [google/magika#41]
If you have Python >= 3.12 you get the `0.1.0` release which is basically empty, please consider yanking the release, so it's not picked up.

**Comment by invernizzi** [comment]
Thanks for the suggestion. We've yanked it.

**Comment by reyammer** [comment]
magika already supports python 3.8 at the moment. The question is whether to drop support for it for future versions and add support for 3.12 instead. See https://github.com/google/magika/issues/43. Please follow up in that issue if you have comments on this. Thanks!
