### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] MineCraft Anvil region

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#411]
**What type of file would you like magika to detect?**
MineCraft Anvil region (.mca)

**What software can create/open these files?**
[NBTExplorer](https://github.com/jaquadro/NBTExplorer)

**Where can these files be found?**
AppData\Roaming\.minecraft\saves\<world name>\region
Must be Minecraft Java Edition 1.2.1 or later.

**If possible, please provide a specification for this file type.**
 
**Additional context**
https://minecraft.wiki/w/Region_file_format

**Comment by corkamig** [comment]
Thanks! Quite a sparse Minecraft-related data dump - definitely hard to identify.
