### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] MineCraft Region

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#412]
**What type of file would you like magika to detect?**
MineCraft Region (.mcr)

**What software can create/open these files?**
[NBTExplorer](https://github.com/jaquadro/NBTExplorer)

**Where can these files be found?**
AppData\Roaming\.minecraft\saves\<world name>\region
Must be Minecraft Java Edition Beta 1.3 to version 1.2.0.

**If possible, please provide a specification for this file type.**

 
**Additional context**
https://minecraft.wiki/w/Region_file_format

**Comment by corkamig** [comment]
Thanks!
A very sparse format, hard to identify...
