### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Pico-8

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#413]
**What type of file would you like magika to detect?**
Pico-8 (.pod)

**What software can create/open these files?**
[PICO-8](https://www.lexaloffle.com/pico-8.php?#getpico8) Fantasy Console

**Where can these files be found?**
https://steamdb.info/tech/Engine/Pico8/
https://www.lexaloffle.com/pico-8.php
https://www.lexaloffle.com/bbs/?cat=7&carts_tab=1#mode=carts&sub=2

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by corkamig** [comment]
Thanks!
Pico-8 uses steanography 🤯 over standard PNG 🤦 for its `.p8.png` cartridge
https://pico-8.fandom.com/wiki/P8PNGFileFormat

This format specifically is Pico-8 POD Data Archive (starting with `CPOD`) but doesn't seem documented anywhere ?

Picotron (successor of Pico-8) uses Pods too - cf https://www.lexaloffle.com/picotron.php?page=faq, https://www.lexaloffle.com/dl/docs/picotron_pod.html but it's a different format altogether.
