### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] OHRRPGCE File

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#420]
**What type of file would you like magika to detect?**
OHRRPGCE (.rpg)

**What software can create/open these files?**
[ohrrpgce/nohrio](https://github.com/ohrrpgce/nohrio)
[lunarlabs/HamsterTools](https://github.com/lunarlabs/HamsterTools)

**Where can these files be found?**
https://rpg.hamsterrepublic.com/ohrrpgce/Where_can_I_find_games%3F
[rversteegen/spirit-zones](https://github.com/rversteegen/spirit-zones)
[horsepie/ratsim2k](https://github.com/horsepie/ratsim2k)

**If possible, please provide a specification for this file type.**
 
**Additional context**
https://rpg.hamsterrepublic.com/ohrrpgce/Main_Page

**Comment by MichaelHinrichs** [comment]
Lol, 420. Nice.

**Comment by corkamig** [comment]
Thanks for the submission!

FTR the format is https://rpg.hamsterrepublic.com/ohrrpgce/RPG_format#Lump_Format which is header-less,
but the files may start with `ARCHINYM.LMP` or `BROWSE.TXT`.
