### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Odin 

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#421]
**What type of file would you like magika to detect?**
Odin

**What software can create/open these files?**

**Where can these files be found?**
https://github.com/search?q=language%3AOdin&type=repositories

**If possible, please provide a specification for this file type.**
https://odin-lang.org/docs/spec/
https://odin-lang.org/docs/overview/
 
**Additional context**
https://odin-lang.org/
[GitHub](https://github.com/odin-lang/Odin)
[Discord](https://discord.com/invite/sVBPHEv)
[Twitch](https://www.twitch.tv/ginger_bill)
[YouTube](https://www.youtube.com/channel/UCUSck1dOH7VKmG4lRW7tZXg)

**Comment by corkamig** [comment]
Thanks! We'll likely add it!
