### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Zig

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#422]
**What type of file would you like magika to detect?**
Zig (.zig)

**What software can create/open these files?**
https://ziglang.org/download/

**Where can these files be found?**
https://github.com/search?q=language%3AZig&type=repositories

**If possible, please provide a specification for this file type.**
https://ziglang.org/documentation/0.12.0/
 
**Additional context**
https://ziglang.org/
https://github.com/ziglang/zig
https://github.com/ziglang/zig/wiki/Community

**Comment by corkamig** [comment]
Thanks! We'll consider it!
