### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Tyrano Scene

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#423]
**What type of file would you like magika to detect?**
Tyrano Scene (.ks)

**What software can create/open these files?**
https://tyranobuilder.com/
https://brokenhammergames.itch.io/ks-converter

**Where can these files be found?**
https://steamdb.info/tech/Engine/TyranoBuilder/
https://itch.io/games/made-with-tyranobuilder
https://rpgmaker.net/games/?engine=48

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by corkamig** [comment]
Thank you! It's quite like the INI text format.
We'll consider it!
