### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Apple iWork Suite

### ISSUE THREAD

**Issue by hardboydu** [google/magika#427]
**What type of file would you like magika to detect?**

Apple iWork Documents(.pages)
Apple iWork Spreadsheets(.numbers)
Apple iWork Presentations(.key)

**What software can create/open these files?**

Apple iWork Suite

**Where can these files be found?**

* Generate these types of files with Apple iWork Suite on Mac OS X
* http://fileformats.archiveteam.org/wiki/IWork
 
**Additional context**

https://fileinfo.com/extension/pages
https://fileinfo.com/extension/iwa

**Comment by reyammer** [comment]
Thanks, adding to our KB for consideration for new version. Closing for now, thanks!
