### ISSUE TITLE
Add typescript type definitions for js lib

### ISSUE THREAD

**Issue by chris-si** [google/magika#44]
Hi,

it would be great if you could add or auto generate type definitions for the js lib so it can be used with typescript.

Since there isn't a CI job to handle automatic releases and I'm not aware of your release process and plans for the lib, I'd rather not myself create a PR for this yet.

**Comment by elhadjaoui** [comment]
facing the same issue :
Could not find a declaration file for module 'magika'. '/node_modules/magika/magika.js' implicitly has an 'any' type.

**Comment by reyammer** [comment]
Thanks for reporting, looking into it.

**Comment by reyammer** [comment]
See #129, not sure if it's related.

**Comment by glassonion1** [comment]
I tried adding types to DefinitelyTyped to use Magika with TypeScript. However, I encountered the following error, and the tests did not pass. Does Magika not support CommonJS?
```
A require call resolved to an ESM JavaScript file, which is an error in Node and some bundlers. CommonJS consumers will need to use a dynamic import.
```
DefinitelyTyped's pull request is below:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68765

**Comment by glassonion1** [comment]
@reyammer 
It appears that Magika will indeed support CommonJS, as shown in https://github.com/google/magika/issues/129. This suggests that we should be able to add types to DefinitelyTyped.

`module.exports = { Magika };`

**Comment by glassonion1** [comment]
@chris-si
I have added type definitions for Magika to DefinitelyTyped. With this, you can now run it in TypeScript without any errors. 

npm: https://www.npmjs.com/package/@types/magika

Please execute the following command.
```
npm install --save-dev @types/magika
```
or
```
pnpm add -D @types/magika
```

Additional information:
Magika did not support CommonJS and didn't pass the tests at DefinitelyTyped, the DefinitelyTyped team has been modified to allow the tests to pass even if the library does not support CommonJS.

**Comment by invernizzi** [comment]
We've published a version with commonJS support, and the library has been rewritten in Typescript as of yesterday. 
Our types should be bundled with the package. Please take a look and let me know if they are as expected.

**Comment by chris-si** [comment]
That's great to hear! I'll give it a try in the coming days.

**Comment by invernizzi** [comment]
Thanks for the quick check! Agreed on both points. 0.2.12 accepts Uint8Array and drops Buffer for non-Node magika.

**Comment by chris-si** [comment]
I tried it out and it works like expected! Thanks for improving the js/ts lib!
