### ISSUE TITLE
Incorrectly Identifies hwp files as xls

### ISSUE THREAD

**Issue by OctopusET** [google/magika#51]
![image](https://github.com/google/magika/assets/18513799/b11bedf5-b20d-4120-a1d7-4cebe23b9a7f)

HWP format is the popular document format in South Korea, developed by hancom.

Here's an example file. (.hwpx file is computer readable format for hancom document)
[sample.zip](https://github.com/google/magika/files/14313011/sample.zip)

See also:
https://github.com/freedomofpress/dangerzone/pull/460 
https://bugs.astron.com/view.php?id=467
https://bugs.documentfoundation.org/show_bug.cgi?id=144747

**Comment by reyammer** [comment]
Thank you, marked this down for next iterations.
