### ISSUE TITLE
[Misdetection] Corrupted HTML file misdetected as ISO

### ISSUE THREAD

**Issue by xiangchen96** [google/magika#521]
**What should the file have been detected as? What has the file been misdetected as?**
A html with a lot of null files at the beginning is being detected as ISO.

**Please link or attach the misdetected file below** (Do NOT upload PII!)
[magika_report.html.zip](https://github.com/user-attachments/files/15902113/magika_report.html.zip)

**Additional context**
Less confidence would be nice, currently `0.9999`

**Comment by reyammer** [comment]
Thanks for reporting. Added this to missdetected samples to keep track of future improvements. (CLA was signed: https://opensource.corp.google.com/signcla/search?q=xiangchen96+)
