### ISSUE TITLE
Update to numpy 2.0.0

### ISSUE THREAD

**Issue by Nicba1010** [google/magika#537]
Hi,

I would appreciate an update to numpy 2.0.0, or at least the option to use it. Unless it breaks something badly.

Kindest regards,
Roberto

**Comment by reyammer** [comment]
Thanks for the suggestion! We are working on the next release; we will test this new version of numpy and add it if possible.

**Comment by reyammer** [comment]
Checked a bit more, unfortunately onnxruntime needs numpy<2.0.0. They are planning to add support later on, but not there yet. "Support for numpy 2.0 will be added in a future release." from https://github.com/Microsoft/onnxruntime/releases/tag/v1.18.1. As soon as they add support, we'll be able to bump numpy version as well.

**Comment by reyammer** [comment]
Update: It seems that onnxruntime 1.19 added support for numpy 2.0.0, will give it a try. https://github.com/Microsoft/onnxruntime/releases/tag/v1.19.0
