### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] epub

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#540]
**What type of file would you like magika to detect?**
epub (.epub)

**What software can create/open these files?**
[Calibre](https://calibre-ebook.com/), [Adobe Digital Editions](https://www.adobe.com/solutions/ebook/digital-editions/download.html?red=av), [Librum](https://librumreader.com/), [Apple Books](https://www.apple.com/apple-books/), [EPUB File Reader](http://www.epubfilereader.com/), [Stanza Desktop](https://stanza-desktop.en.softonic.com/), [Okular](https://okular.kde.org/), [Sumatra PDF](https://www.sumatrapdfreader.org/free-pdf-reader), [EPUBReader for Firefox](https://addons.mozilla.org/firefox/addon/epubreader/) and [EPUBReader for Chrome](https://chrome.google.com/webstore/detail/epubreader/jhhclmfgfllimlhabjkgkeebkbiadflb), [Google Play Books](https://play.google.com/books)

**Where can these files be found?**
https://plfa.github.io/plfa.epub
https://www.lifewire.com/download-free-books-3482754

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by stradivari96** [comment]
Epub is already included...

```
magika test.epub
test.epub: EPUB document (document)
```

**Comment by MichaelHinrichs** [comment]
Dang, I missed that.
