### ISSUE TITLE
Clean up magika assets managment

### ISSUE THREAD

**Issue by reyammer** [google/magika#640]
Currently, models and other assets such as KB lives in the python/magika/models dir, with the rust (and js?) codebases pulling things from there. This is not ideal as we may want to decouple the various codebases (and we may want to upgrade one model for python at a different time than for rust). Also, we often work with .onnx format, but for some other stuff we may want the .h5 or the tfjs version... I could store them all in python/magika/models, but they don't belong there... at the moment, whatever is in python/magika/ gets packaged with the pip package, which is not good.

My proposal: I update my code from the training side of things / internal repo to export assets (models + content types KB + whatever else) somewhere like <root_github_repo_dir>/assets/*. Then, the various codebases (python, rust, go, js, etc.) can pick from that folder whatever they want/need (in an automated or manual fashion).

Thoughts?

CC @invernizzi @ia0

**Comment by ia0** [comment]
I also think this is a better design. So all green on my side to proceed. Once you do the base layout, I can update the Rust side of things. Just ping me on the PR.

**Comment by reyammer** [comment]
#643 stores assets in `assets/`, which is the first step. Then, we need to clean up the `assets_generation/` script.

**Comment by reyammer** [comment]
Closing this one as we actually cleaned up `/assets`. Opened #684 to track what we need to clean about `/assets_generation`.
