### ISSUE TITLE
Removing `Cargo.lock` from `rust/lib`

### ISSUE THREAD

**Issue by tugunchinov** [google/magika#646]
Consider adding `Cargo.lock` to `.gitignore` and deleting it from sources. 
After that please update lib's dependencies:

```
[dependencies]
ndarray = "0.16.1"
serde = { version = "1.0.204", features = ["derive"], optional = true }
thiserror = "1.0.63"
tokio = { version = "1.38.1", features = ["fs", "io-util"] }

[dependencies.ort]
version = "2.0.0-rc.5"
default-features = true
features = ["ndarray"]
```

I'd like to use your crate but can't as it has fixed `Cargo.lock` but I have to build it from scratch and it doesn't compile.

**Comment by ia0** [comment]
Did you try `cargo install --locked --path=rust/cli`? Note that we will soon make a release to crates.io, so you would be able to run `cargo install --locked magika-cli` instead.

**Comment by tugunchinov** [comment]
Oh, I wanted to use `rust/lib` in my own project to check files' extensions.

**Comment by ia0** [comment]
I see, in that case the lock file is not used. Soon you'll be able to use crates.io though.

**Comment by tugunchinov** [comment]
Thank you, I'm looking forward to that
