### ISSUE TITLE
Magica is unable to categorise swift file

### ISSUE THREAD

**Issue by shantohx** [google/magika#71]
I was checking the demo and found, it categorise swift as JavaScript.

<img width="1401" alt="Screenshot 2024-02-19 at 3 01 45 AM" src="https://github.com/google/magika/assets/55149956/3b682afa-19b0-42db-a1d8-72d6fab54a1a">

**Comment by kanttouchthis** [comment]
swift is not one of the [supported file types](https://github.com/google/magika/blob/main/docs/supported-content-types-list.md)

**Comment by reyammer** [comment]
Thank you. not supported yet but will consider for v2.

**Comment by reyammer** [comment]
Thanks for reporting! Marked as "to import to our KB", and closing for now, see https://github.com/google/magika/issues/152 for context. Thanks!
