### ISSUE TITLE
Add gh workflow to build python packages for all platforms and publish as artifacts

### ISSUE THREAD

**Issue by reyammer** [google/magika#724]
Steps:
- [x] Disable maturin workflow via github UI; we build via `./python/script/build_python_package.py`
- [x] Disable running python-related workflows when we tag a new version of rust
- [x] Create a new workflow that builds & publish python package artifacts to github when we tag a python version
- [x] Once we are done porting the maturin workflow to our setup, delete the maturin workflow

@ia0, am I missing anything?

**Comment by ia0** [comment]
> * [ ]  Disable running python-related workflows when we tag a new version of rust

Should theoretically not be needed since the tag name won't match those workflows AFAICT. We tag rust as `rust-v*`.

LGTM otherwise.
