### ISSUE TITLE
[Development Setup] [tool.poetry] section not found in magika/python/pyproject.toml

### ISSUE THREAD

**Issue by b1tg** [google/magika#734]
While i follow the Development Setup steps, `poetry shell` gives follow error:

```
[root@exarch python]# pwd
/root/magika/python
[root@exarch python]# poetry --version
Poetry (version 1.7.1)
[root@exarch python]# poetry shell

[tool.poetry] section not found in /root/magika/python/pyproject.toml
[root@exarch python]# 

```

My test environment:

OS: arch linux with kernel 6.10.2
poetry version: 1.7.1

**Comment by reyammer** [comment]
Apologies! We moved to use `uv` and we are revamping the docs as we speak. Here is the draft PR with more updated details, which is still heavy WIP: https://github.com/google/magika/pull/740.

**Comment by reyammer** [comment]
Merged the new docs. See https://github.com/google/magika/blob/main/python/README.md#development-setup for dev setup information, and feel free to open another issue if anything is unclear. Thanks!
