### ISSUE TITLE
Binary file identification is basic compared to GNU file

### ISSUE THREAD

**Issue by berney** [google/magika#75]
I was curious how this compared to GNU `file` for detecting if a binary is statically compiled or not.
Magika correctly identifies the file as an ELF or Mach-o executable, but that's it. It does not go into deeper details like if it is statically linked or which architecture it is for, whether it has debug symbols, stripped, etc., details that `file` will show.

Can plans be clarified as to whether magika is to be more specific with its identification of files, or if it's intentional to limit scope to high level generic classifications (e.g. simple `mach-o`, `elf`), and not get into details like targeted platforms (`amd64`, `arm64`), linking (`statically linked`), runtimes (`Go`), etc.?

# Status Quo `file`
## `file` on release binary
```
$ file release/goss-linux-amd64
release/goss-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=NZ3NC0NaQ1A__VXTMP32/C4GwgAOXz8tq1OWGhmJI/jNyZlKXZG8ghsmw3IBam/kO2y_axJzsqQZmtK9R4a, stripped
```

## `file` on a debug binary
```
$ file debug/goss-linux-amd64
debug/goss-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=schnmn0cqD0OYUAQLlln/nTtv8RRejTipPl0QtX2L/5rh0P1Upx9VxsKYQJ-pN/eZxsN78-M_3elAQC2Na_, with debug_info, not stripped
```

# Magika 
## Magika on a release binary 
```bash
$ docker run --rm -it -v "$(pwd):/src:ro" google/magika /src/release/goss-linux-amd64
/src/release/goss-linux-amd64: ELF executable (executable)
```
## Magika on a debug binary

```bash
$ docker run --rm -it -v "$(pwd):/src:ro" google/magika /src/debug/goss-linux-amd64
/src/debug/goss-linux-amd64: ELF executable (executable)
```

**Comment by reyammer** [comment]
Thanks for the feedback! We have added a question the FAQ that should clarify what Magika aims for / what does not currently aim for. See https://github.com/google/magika/blob/main/docs/faq.md#q-does-magika-return-additional-metadata-other-than-a-content-type-label. Closing this for now, but please feel free re-open if your question is not addressed. Thanks!
