### ISSUE TITLE
0.6.0rc1 doesn't seem to actually be published to PyPi

### ISSUE THREAD

**Issue by romannurik** [google/magika#764]
According to the docs, 0.6.0rc1 is published to PyPi:

> This README is about the soon-to-be released magika 0.6.0 (currently published as 0.6.0rc1 on pypi) …

But I don't see it listed: https://pypi.org/project/magika/#history

And running the documented pip install command doesn't work:

```bash
$ pip install magika==0.6.0rc1
```

**Comment by reyammer** [comment]
Thanks for reporting! We were about to push the rc but we hit some unexpected issues with manylinux (see #752). We are closed to solve the problems, but in the meantime I've updated the README to reflect that the rc is not there yet.

**Comment by romannurik** [comment]
Got it thanks!
