### ISSUE TITLE
manylinux magika wheel does not install on ubuntu 20.04 with pip

### ISSUE THREAD

**Issue by reyammer** [google/magika#781]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

$ cat /proc/cpuinfo | grep vendor_id
vendor_id       : AuthenticAMD

$ python3  --version
Python 3.8.10

$ dpkg -l | grep libc6:amd64
ii  libc6:amd64                        2.31-0ubuntu9.16                  amd64        GNU C Library: Shared libraries

$ pip install ./magika-0.6.0rc1-py3-none-manylinux_2_28_x86_64.whl
ERROR: magika-0.6.0rc1-py3-none-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
```

Unfortunately pip does not tell you why (see https://github.com/pypa/pip/issues/10793).

What's even weirder: the wheel installs correctly (and without warnings) with `uv` on the same VM.

Given the metadata above, the wheel should actually be compatible.

You can get the wheel here: https://github.com/google/magika/actions/runs/11631673973

The test VM is just an ubuntu 20.04 VM on GCE.

Thoughts @ia0 @invernizzi?

**Comment by ia0** [comment]
The wheel also installs in the maturin container (see `Run before script` under `Test wheels` in #783). However the container doesn't seem to be Ubuntu 20.04 but a container with an old enough libc: `quay.io/pypa/manylinux_2_28_x86_64:latest`. It might be the python version: 3.11.9 in the maturin container and 3.8.10 for you.

**Comment by gaby** [comment]
@reyammer Python 3.8 is EOL since laet month. Is the plan to still support it?

Try doing a verbose install, maybe that says something

**Comment by reyammer** [comment]
It seems there is no way to get more info from pip, even with verbose (see https://github.com/pypa/pip/issues/10793), BUT: using a more recent version of pip worked out!

On the old ubuntu VM I'm playing with, pip comes from the `python3-pip` deb package (`20.0.2-5ubuntu1.11`). But if I use a more recent version of pip, the wheel seems to install successfully!

Steps:
- `python3 -m pip install --upgrade pip`
- `python3 -m pip install path/to/wheel.whl`

So, everything seems working, closing this for now. We should have all we need to finally publish an `-rc` to pypi.

[About dropping support for 3.8: for now it's now supporting it is not creating issues, so I would leave everything as is until we run into problems?]
