### ISSUE TITLE
Extend test "uv add magika.whl" to windows runner

### ISSUE THREAD

**Issue by reyammer** [google/magika#805]
We recently updated our python github workflows to test that the magika package/wheels can be installed with `uv add` (in addition to `pip install magika`). To test this, we use a one-liner that currently works only for ubuntu and macos. We need to extend the one-liner (or add another one) so that it also works for Windows.

These are the workflows to update:
- [ ] https://github.com/google/magika/blob/main/.github/workflows/python-test-published-package.yml
- [ ] https://github.com/google/magika/blob/main/.github/workflows/python-test-published-rc-package.yml
- [ ] https://github.com/google/magika/blob/main/.github/workflows/python-build-package.yml

**Comment by Mohit-Gaur** [comment]
@reyammer I'd like to take a stab at this

**Comment by reyammer** [comment]
Go for it, thanks! Assigned it. The idea would be to add another if, and for windows use some powershell-like syntax to implement the same one-liner. Let me know if you have questions or something is not clear.
