### ISSUE TITLE
[NEW FILE TYPE REQUEST]

### ISSUE THREAD

**Issue by mrmcelwee44** [google/magika#81]
**What type of file would you like magika to detect?**
Examples:
 - "Nintendo Binary Revolution RESource (.brres)"
 - "Valve Map Format file (.vmf)"
 - "Blender save file (.blend)"
 - "RPG Maker 2000/2003 Lcf DataBase (.ldb)"
 - "COLLADA file (.dae)"
 - "Unreal Engine Asset (.uasset)"

**What software can create/open these files?**
Examples:
 - "[BrawlCrate](https://github.com/soopercool101/BrawlCrate)"
 - "Valve Hammer Editor, included with any Source Engine game on Steam."
 - "[Blender](https://www.blender.org/download/)"
 - "[RPG Maker 2003](https://www.rpgmakerweb.com/products/rpg-maker-2003), [easyRPG](https://easyrpg.org/), Wolf RPG Editor"
 - "Many 3D modleing softwares."
 - "[Unreal Engine](https://www.unrealengine.com/en-US)"
 - "Any text editor."

**Where can these files be found?**
Examples:
 - "Dump the ISO of any of [these Wii games](https://wiki.vg-resource.com/BRRES#List_of_games_using_the_format)"
 - "Use [Crowbar](https://github.com/ZeqMacaw/Crowbar) to decompile the BSP files of any Source Engine game. Maybe use [GCFScape](https://nemstools.github.io/pages/GCFScape-Download.html) to extract even more BSPs from 'dir.vpk' files. Make your own in Hammer."
 - "https://blendermarket.com/categories/models, https://www.turbosquid.com/Search/3D-Models/marketplace/blend, https://sketchfab.com/store/3d-models/blend?ref=store-home"
 - "Any RPGMaker 2000/2003 game."
 - "[Unreal Marketplace](https://www.unrealengine.com/marketplace/en-US/store)"
 - "placeholder.zip"

**If possible, please provide a specification for this file type.**
Examples:
 - "https://wiki.tockdom.com/wiki/BRRES_(File_Format), https://horizon.miraheze.org/wiki/.brres"
 - "https://developer.valvesoftware.com/wiki/VMF_(Valve_Map_Format)"
 - "https://www.collada.org/2008/03/COLLADASchema"
 - "https://gota7.github.io/NitroStudio2/specs/sequenceArchive.html"
 - "http://www.amnoid.de/gc/Rarc.txt, https://kuribo64.net/wiki/?page=RARC, https://wiki.tockdom.com/wiki/RARC_(File_Format)"
 - "https://www.3dbrew.org/wiki/CGFX, https://mk3ds.com/index.php?title=CGFX_(File_Format)"
 - "https://mk8.tockdom.com/wiki/BFRES_(File_Format)", https://wiki.vg-resource.com/BFRES, https://wiki.oatmealdome.me/BFRES_(File_Format)"
 
**Additional context**

**Comment by reyammer** [comment]
seems empty, closing.

**Comment by mrmcelwee44** [comment]
Link
