### ISSUE TITLE
[NEW FILE TYPE REQUEST] Autodesk Revit and Autodesk AutoCAD

### ISSUE THREAD

**Issue by s0ar** [google/magika#83]
**What type of file would you like magika to detect?**
Examples:
 - revitsample.rfa
 - drawing.dwg

**What software can create/open these files?**
Examples:
 - Autodesk Revit
 - Autodesk AutoCAD

**Where can these files be found?**
Examples:
 - https://help.autodesk.com/view/RVT/2022/ENU/?guid=GUID-7B9C7A69-1083-406D-A01F-53D405C167F3
 - https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/6XGQklp3ZcBFqljLPjrnQ9.html

**Comment by reyammer** [comment]
Thanks for reporting! Marked as "to import to our KB", and closing for now, see https://github.com/google/magika/issues/152 for context. Thanks!
