### ISSUE TITLE
Test support for Mac OS

### ISSUE THREAD

**Issue by reyammer** [google/magika#88]

**Comment by gaby** [comment]
@reyammer This should be doable using githuh workflows. I can send a Pull Request

**Comment by reyammer** [comment]
Thanks! Is there a way to test the actual magika package that people install from pip, rather than just running the tests in a macos environment? my current gh workflow does the latter, but we may want to improve.

**Comment by invernizzi** [comment]
Much appreciated, @gaby! 
Ideally, we'd like to build some decent CI for all sort of platforms. So, bonus points if your PR can be used to start something like that.

**Comment by reyammer** [comment]
IIRC you can specify something like this in gh action: `os: [ubuntu-22.04, macos-latest, windows-latest]`. Is this the direction, @gaby?

But independently from this, the current CI does "poetry install + pytests tests"... which is a good starting point, but not THE tests I would also like to have... ideally we should test for "what people install with pip install magika". Created #158 to track this additional aspect.

**Comment by gaby** [comment]
@reyammer Correct, that will run the tests in that enviroment.

I was thinking that you could have a workflow that does the pip install and runs against the `tests_data/` directory to verify it can run on that platform

**Comment by ehjmx** [comment]
I have Python 3.12 installed via MacPorts on macOS 14.3.1. on a MacBookPro 13inch M2

When I try to install magika with pip312 I get the following error message:
```
pip-3.12 install magika
Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following yanked versions: 0.1.0
ERROR: Ignored the following versions that require a different python version: 0.5.0 Requires-Python >=3.8,<3.12
ERROR: Could not find a version that satisfies the requirement magika (from versions: none)
ERROR: No matching distribution found for magika
```
I haven't tried the pip3 which comes with the latest XCode. It might work as python3 --version gives me 3.9.6

**Comment by gaby** [comment]
@ehjmx Probably needs to be installed in a venv. The dependencies are conflicting with the ones from the OS

**Comment by gaby** [comment]
I'm updating the workflows to run on multiple platforms/python version. I can confirm that the tests only pass on `linux` and `macos`. When using `windows` a significant amount of tests are failing.
