### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] RPG Maker VX Ace rgss3a file

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#95]
**What type of file would you like magika to detect?**
RPG Maker VX Ace RGSS encrypted archive (.rgss3a)

**What software can create/open these files?**
[RPG Maker RPG Maker VX Ace](https://www.rpgmakerweb.com/products/rpg-maker-vx-ace), [RPG Maker Decrypter](https://github.com/uuksu/RPGMakerDecrypter), [RGSS Decryptor](https://github.com/usagirei/RGSS-Decryptor), [game resources viewer](https://dinaki.itch.io/game-resources-viewer).

**Where can these files be found?**
Many RPG Maker RPG Maker VX Ace games. Use RPG Maker RPG Maker VX Ace to compress your own.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see https://github.com/google/magika/issues/152 for context. Thanks!
