### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] GameMaker data file

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#97]
**What type of file would you like magika to detect?**
GameMaker data (data.win)

**What software can create/open these files?**
[GameMaker Studio](https://gamemaker.io/en), [Undertale Mod Tool](https://github.com/UnderminersTeam/UndertaleModTool).

**Where can these files be found?**
The Windows version of any GameMaker game. Some GameMaker games are packaged as a standalone executable, but the data.win file can be found inside if you unzip the exe.

**If possible, please provide a specification for this file type.**
 
**Additional context**

**Comment by reyammer** [comment]
Closing, see https://github.com/google/magika/issues/152 for context. Thanks!
