### ISSUE TITLE
[NEW CONTENT TYPE REQUEST] Valve Material

### ISSUE THREAD

**Issue by MichaelHinrichs** [google/magika#99]
**What type of file would you like magika to detect?**
Valve Texture Format (.vtf)

**What software can create/open these files?**
[vtex](https://developer.valvesoftware.com/wiki/VTEX_(Source)), included with any valve published Source Engine game.
[VTFEdit](https://nemstools.github.io/pages/VTFLib-Download.html)
[VTF Edit Revitalized](https://github.com/Trico-Everfire/VTF_Edit_Revitalized)
[VTF Editor](https://github.com/Mishcatt/VTF-Editor)

**Where can these files be found?**
Many Source Engine games. Convert TGA files to VTF using the above tools. Use [GCFScape](https://nemstools.github.io/pages/GCFScape-Download.html) to extract even more VTFs from 'dir.vpk' files, and sometimes BSP files too.

**If possible, please provide a specification for this file type.**

**Additional context**
https://developer.valvesoftware.com/wiki/VTF_(Valve_Texture_Format)

**Comment by reyammer** [comment]
Closing, see https://github.com/google/magika/issues/152 for context. Thanks!
